#!/usr/bin/env bash
# This bash (init) script that manages manage_my_process

file="/var/run/my_process.pid"

function_start()
{
    ./manage_my_process &
    echo "$!" > "$file"
}

function_stop()
{
    kill "$(cat $file)"
    rm $file
}

case "$1" in
    start)
        function_start
        echo "manage_my_process started"
        ;;
    stop)
        function_stop
        echo "manage_my_process stopped"
        ;;
    restart)
        function_stop
        function_start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
