#!/usr/bin/env bash
# This script that displays the content of the file /etc/passwd, only username, user id and home directory path for the user

while read -r line
do
    echo "$line" | cut -d : -f1,4,6
done < /etc/passwd
