#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd in the format: "The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"

while IFS=: read -r USRNAME PASSWD USR_ID GROUP_ID USR_ID_INFO HOME_DIRECTORY CSHELL
do
    echo "The user $USRNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $CSHELL. $USR_ID's place is protected by the passcode $PASSWD, more info about the user here: $USR_ID_INFO"
done < /etc/passwd
