#!/usr/bin/env bash
# This scipt displays "Holberton School" ten times, but in the 9th iteration print Hi

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 10 ]
    then
        echo "Hi"
    fi
    echo "Holberton School"
    ((i++))
done
