#!/usr/bin/env bash
# This scipt displays bad luck for the 4th loop iteration, good luck for the 8th loop iteration or Holberton School for the other iterations

i=1

while [ $i -le 10 ]
do
    if [ $i == 4 ]
    then
        echo "bad luck"
    elif [ $i == 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i++))
done
