#!/usr/bin/env bash
# Script that configures localhost to 127.0.0.2 and facabook.com to 8.8.8.8

cp /etc/hosts ~/new_host
sed -i s/127.0.0.1/127.0.0.2/ ~/new_host
echo "8.8.8.8 facebook.com" >> ~/new_host
cp -f ~/new_host /etc/hosts
